export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAILURE = 'REQUEST_FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';

export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES';

export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
export const ARTICLE_COMMENT_SUCCESS = 'ARTICLE_COMMENT_SUCCESS';
