export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const HOME_SIDE_AD_GET_ENTITY_SUCCESS = 'HOME_SIDE_AD_GET_ENTITY_SUCCESS';
export const HOME_SIDE_TOPIC_GET_LISTS_SUCCESS = 'HOME_SIDE_TOPIC_GET_LISTS_SUCCESS';
export const HOME_SIDE_TAG_GET_LISTS_SUCCESS = 'HOME_SIDE_TAG_GET_LISTS_SUCCESS';
export const HOME_SIDE_LINK_GET_LISTS_SUCCESS = 'HOME_SIDE_LINK_GET_LISTS_SUCCESS';

export const ACCOUNT_LOGIN_STATUS_CHANGED = 'ACCOUNT_LOGIN_STATUS_CHANGED';
export const ACCOUNT_LOGIN_SUCCESS = 'ACCOUNT_LOGIN_SUCCESS';
export const ACCOUNT_LOGOUT_SUCCESS = 'ACCOUNT_LOGOUT_SUCCESS';

export const CATEGORY_GET_LISTS_SUCCESS = 'CATEGORY_GET_LISTS_SUCCESS';
export const CATEGORY_GET_ENTITY_SUCCESS = 'CATEGORY_GET_ENTITY_SUCCESS';

export const USER_GET_ENTITY_SUCCESS = 'USER_GET_ENTITY_SUCCESS';

export const TOPIC_INDEX_GET_DATA_SUCCESS = 'TOPIC_INDEX_GET_DATA_SUCCESS';
export const TOPIC_INDEX_GET_LISTS_SUCCESS = 'TOPIC_INDEX_GET_LISTS_SUCCESS';
export const TOPIC_DETAIL_GET_DATA_SUCCESS = 'TOPIC_DETAIL_GET_DATA_SUCCESS';
export const TOPIC_DETAIL_GET_LISTS_SUCCESS = 'TOPIC_DETAIL_GET_LISTS_SUCCESS';
export const TOPIC_GET_LISTS_SUCCESS = 'TOPIC_GET_LISTS_SUCCESS';
export const TOPIC_GET_ENTITY_SUCCESS = 'TOPIC_GET_ENTITY_SUCCESS';
export const TOPIC_ARTICLE_GET_LISTS_SUCCESS = 'TOPIC_ARTICLE_GET_LISTS_SUCCESS';

export const ARTICLE_GET_LISTS_SUCCESS = 'ARTICLE_GET_LISTS_SUCCESS';
export const ARTICLE_GET_ENTITY_SUCCESS = 'ARTICLE_GET_ENTITY_SUCCESS';

export const TAG_GET_LISTS_SUCCESS = 'TAG_GET_LISTS_SUCCESS';
export const TAG_GET_ENTITY_SUCCESS = 'TAG_GET_ENTITY_SUCCESS';

export const NOTIFICATION_GET_LISTS_SUCCESS = 'NOTIFICATION_GET_LISTS_SUCCESS';
export const NOTIFICATION_GET_ENTITY_SUCCESS = 'NOTIFICATION_GET_ENTITY_SUCCESS';

export const ASSET_GET_LISTS_SUCCESS = 'ASSET_GET_LISTS_SUCCESS';
export const ASSET_CREATE_ENTITY_SUCCESS = 'ASSET_CREATE_ENTITY_SUCCESS';

export const SEARCH_USER_GET_LISTS_SUCCESS = 'SEARCH_USER_GET_LISTS_SUCCESS';
export const SEARCH_TOPIC_GET_LISTS_SUCCESS = 'SEARCH_TOPIC_GET_LISTS_SUCCESS';
export const SEARCH_ARTICLE_GET_LISTS_SUCCESS = 'SEARCH_ARTICLE_GET_LISTS_SUCCESS';

export const QINIU_GET_TOKEN_SUCCESS = 'QINIU_GET_TOKEN_SUCCESS';
